### PR TITLE
Add tensorflow 2.0 support

### PR DESCRIPTION
**Pull request by gilzamir18**
I made this small adaptation to work in tensorflow 2.0. If you add it to the pip repository, it will be cool.

Thank you.

### CODE REVIEW

**Comment by mrahtz** [comment]
Thanks for the PR!

When I run the tests with TensorFlow 2.4.1, I'm getting:

```
======================================================================
ERROR: test_set_writer (__main__.TestEasyTFLog)
Check that when using an EventFileWriter from a FileWriter,
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 53, in test_set_writer
    writer = tf.compat.v1.summary.FileWriter('logs')
  File "/usr/local/lib/python3.8/site-packages/tensorflow/python/summary/writer/writer.py", line 359, in __init__
    raise RuntimeError(
RuntimeError: v1.summary.FileWriter is not compatible with eager execution. Use `tf.summary.create_file_writer`,or a `with v1.Graph().as_default():` context
```

Could you fix this test so that it works for both TF1 and TF2?

**Comment by gilzamir18** [comment]
Hi Matthew, the easiest way to do this is to disable eager execution mode in the tests.py file. At least it is a temporary solution. The ideal would be to adapt the code to use the new tensorflow API. As soon as I finish a project I'm involved in, I look for a better solution. But I've already made changes that work. Thanks for your project, you are helping me with some tasks.

**Comment by gilzamir18** [comment]
Hi dear, i made an adaptation that compiles in both tf1 and tf2, but it may not be the most elegant adaptation, however, it passed the tests. The tests were done using tensorflow 1.15 and the latest version 2.4.1.

Setup: 
       Ubuntu 18.04
       Python 3.6.9
       Test 1: tensorflow 1.15 OK
       Test 2: tensorflow 2.4.1 OK

**Comment by mrahtz** [comment]
Thanks for the change! This weekend is looking busy but I'll try to take a look soon.

**Comment by mrahtz** [comment]
Looks good. Thanks!

**Comment by mrahtz** [comment]
Have just uploaded the new version, 1.12, to PyPI too.

**Pull request merged**
